AWSTemplateFormatVersion: 2010-09-09


# A CloudFormation template to create/configure an AWS RDS based on parameters,
# along with an associated security group and subnet group.
#
# You can specify engine name and engine versions, the instance class type.
#
#this template requires the name of an existing vpc stack and securitygrp stack as
# a parameter.
#
Description: 'AWS CloudFormation Sample Template RDS'

Parameters:

  EnvironmentValue:
    AllowedValues:
      - preprod
      - dev
      - pt
      - prod
    Default: preprod
    Description: Type of the environment
    Type: String
  TechnicalOwner:
    Description: Technical Owner
    Type: String

  Application:
    Type: String
    Default: 'sonata'
    Description: Application Name
    
  Partition:
    Description: Delimiter for partition
    Type: String
    Default: '-'
    ConstraintDescription: Must be a string literal


  NetworkStackName:
    Description: Name of an active CloudFormation stack that contains networking resources
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"

  SecurityGroupStackName:
    Description: 'Stack name of  securitygroups.'
    Type: String

  DatabaseUser:
    Default: admin
    Type: String
    Description: Database admin account name
    MinLength: 5
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Name must begin with a letter and contain only alphanumeric characters

  DatabasePassword:
    NoEcho: true
    Type: String
    Description: Database admin account password
    MinLength: 6
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Password must contain only alphanumeric characters

  DatabaseName:
    Default: StartupDB
    Type: String
    Description: Database name
    MinLength: 1
    MaxLength: 30
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Name must begin with a letter and contain only alphanumeric characters

  DatabaseSize:
    Default: 100
    Type: Number
    Description: Database storage size in gigabytes (GB)
    MinValue: 5
    ConstraintDescription: Enter a size of at least 5 GB

  StorageType:
    Description: Specifies the storage type to be associated with the DB instance.
    AllowedValues:
      - standard 
      - gp2 
      - io1
    Default: gp2
    Type: String  

  DBSnapshotIdentifier:
    Description: 'Optional name or Amazon Resource Name (ARN) of the DB snapshot from which you want to restore (leave blank to create an empty database).'
    Type: String
    Default: ''

#  ProvisionedIopsValue:
#    Description: "(Skip if Not Using Provisioned IOPS) Set Provisioned IOPS 1000-256000."
#    Type: Number
#    Default: 1000
#    MinValue: 1000
#    MaxValue: 256000

  # Default is 500 MB
  DatabaseAlarmMinFreeSpaceInBytes:
    Default: 524288000
    Type: Number
    Description: Number of min free space bytes for alarm (if enabled)
    MinValue: 1
    ConstraintDescription: A value of one byte or more

  # Default is 200 MB
  DatabaseAlarmSwapUsageInBytes:
    Default: 209715200
    Type: Number
    Description: Number of swap usage bytes for alarm (if enabled)
    MinValue: 1
    ConstraintDescription: A value of one byte or more

  DBEngine:
    Description: The database engine
    Type: String
    Default: MySQL
    AllowedValues: [aurora-mysql, aurora-postgresql, mariadb, MySQL, -'ee, -'se2, postgres, sqlserver-ee, sqlserver-se, sqlserver-ex, sqlserver-web]
    ConstraintDescription: must select a valid database Engine type.

  EngineVersion:
    Description: 'select the engine version'
    Type: String
    Default: '8.0.28'
    AllowedValues: ['8.0.28','8.0.27','8.0.26','8.0.25','8.0.23','8.0.21','8.0.20','8.0.19',
      '8.0.17','8.0.16','8.0.15','8.0.13','8.0.11','5.7.37','5.7.34','5.7.33','5.7.31',
      '5.7.30','5.7.28','5.7.26','5.7.25','5.7.24','5.7.23','5.7.22','5.7.21','5.7.19','5.7.17','5.7.16',
      '5.6.51','5.6.49','5.6.48','5.6.46','5.6.44','5.6.43','5.6.41','5.6.40','5.6.39',
      '5.6.37','5.6.35','5.6.34', '10.6.7', '10.6.5', '10.5.15', '10.5.13', '10.5.12', '10.5.9', '10.5.8',
       '10.4.24', '10.4.22', '10.4.21', '10.4.18', '10.4.13', '10.3.34', '10.3.32', '10.3.31',
       '10.3.28', '10.3.23', '10.3.20', '10.3.13', '10.3.8', '10.2.43', '10.2.41', '10.2.40', '10.2.39',
       '10.2.37', '10.2.32', '10.2.21', '10.2.15', '10.2.12', '10.2.11', '13.3-R1', '13.5-R1', '13.6-R1',
       '13.4-R1', '14.1-R1', '14.2-R1', '12.7-R1', '12.8-R1', '12.9-R1', '12.10-R1', '11.12-R1',
       '11.13-R1', '11.14-R1', '11.15-R1', '10.17-R1', '10.18-R1', '10.19-R1', '10.20-R1', '9.6.22-R1',
       '9.6.23-R1', '9.6.24-R1', '12.1.0.2.v1', '12.1.0.2.v2', '12.1.0.2.v3', '12.1.0.2.v4', '12.1.0.2.v5', '12.1.0.2.v6',
       '12.1.0.2.v7', '12.1.0.2.v8', '12.1.0.2.v9', '12.1.0.2.v10', '12.1.0.2.v11', '12.1.0.2.v12', '12.1.0.2.v13', '12.1.0.2.v14',
       '12.1.0.2.v15', '12.1.0.2.v16', '12.1.0.2.v17', '12.1.0.2.v18', '12.1.0.2.v19', '12.1.0.2.v20', '12.1.0.2.v21', '12.1.0.2.v22',
       '12.1.0.2.v23', '12.1.0.2.v24', '12.1.0.2.v25', '12.1.0.2.v26', '12.1.0.2.v27', '19.0.0.0.ru-2019-07.rur-2019-07.r1', '19.0.0.0.ru-2019-10.rur-2019-10.r1',
       '19.0.0.0.ru-2020-01.rur-2020-01.r1', '19.0.0.0.ru-2020-04.rur-2020-04.r1', '19.0.0.0.ru-2020-07.rur-2020-07.r1', '19.0.0.0.ru-2020-10.rur-2020-10.r1',
       '19.0.0.0.ru-2021-01.rur-2021-01.r1', '19.0.0.0.ru-2021-04.rur-2021-04.r1', '19.0.0.0.ru-2021-07.rur-2021-07.r1', '19.0.0.0.ru-2021-10.rur-2021-10.r1',
       '19.0.0.0.ru-2021-01.rur-2021-01.r2', '19.0.0.0.ru-2022-01.rur-2022-01.r1',  '15.00.4198.2.v1', '15.00.4153.1.v1', '15.00.4073.23.v1',
      '15.00.4043.16.v1', '14.00.3421.10.v1', '14.00.3401.7.v1', '14.00.3381.3.v1', '14.00.3356.20.v1',
      '14.00.3294.2.v1', '14.00.3281.6.v1', '13.00.6300.2.v1',  '13.00.5882.1.v1', '13.00.5850.14.v1', '13.00.5820.21.v1',
      '13.00.5598.27.v1', '12.00.6329.1.v1', '12.00.6293.0.v1', '12.00.5571.0.v1']

  EncryptionAtRest:
    Default: false
    Type: String
    Description: The optional flag for encryption at rest (db.t2.small and above)
    ConstraintDescription: Only true or false are allowed
    AllowedValues:
      - true
      - false

  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t2.small
    AllowedValues: [db.t1.micro, db.m1.small, db.m1.medium, db.m1.large, db.m1.xlarge,
      db.m2.xlarge, db.m2.2xlarge, db.m2.4xlarge, db.m3.medium, db.m3.large, db.m3.xlarge,
      db.m3.2xlarge, db.m4.large, db.m4.xlarge, db.m4.2xlarge, db.m4.4xlarge, db.m4.10xlarge,
      db.r3.large, db.r3.xlarge, db.r3.2xlarge, db.r3.4xlarge, db.r3.8xlarge, db.m2.xlarge,
      db.m2.2xlarge, db.m2.4xlarge, db.cr1.8xlarge, db.t2.micro, db.t2.small, db.t2.medium,
      db.t2.large]



  DBMultiAZ:
    Description: 'Specifies if the database instance is deployed to multiple Availability Zones for HA.'
    Type: String
    Default: false
    AllowedValues: [true, false]
  DBBackupRetentionPeriod:
    Description: 'The number of days to keep snapshots of the database.'
    Type: Number
    MinValue: 0
    MaxValue: 35
    Default: 7
  PreferredBackupWindow:
    Description: 'The daily time range in UTC during which you want to create automated backups.'
    Type: String
    Default: '09:54-10:24'

  AllowMajorVersionUpgrade:
    Description: A value that indicates whether major version upgrades are allowed
    Type: String
    Default: false
    AllowedValues: [true, false]

  AutoMinorVersionUpgrade:
    Description: A value that indicates whether Minor version upgrades are allowed
    Type: String
    Default: false
    AllowedValues: [true, false]

  PubliclyAccessible:
    Description: Indicates whether the DB instance is an internet-facing instance
    Type: String
    Default: false
    AllowedValues: [true, false]

  #PreferredMaintenanceWindow:
  #  Description: The weekly time range (in UTC) during which system maintenance can occur.
  #  Type: String
  #  Default: 'sat:07:00-sat:07:30'
  EnableIAMDatabaseAuthentication:
    Description: 'Enable mapping of AWS Identity and Access Management (IAM) accounts to database accounts'
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
#  DBOptionGroupName:
#   Description: 'Optional name of an existing DB option group.'
#    Type: String
#    Default: ''
# DBParameterGroupName:
#  Description: 'Optional name of an existing DB parameter group.'
#  Type: String
#  Default: ''
  DeletionProtection:
    Default: false
    Type: String
    Description: The database can't be deleted when deletion protection is enabled
    ConstraintDescription: Only true or false are allowed
    AllowedValues:
      - true
      - false

  DatabaseAlarmMaxCpuPercent:
    Description: Database CPU % max for alarm
    Type: Number
    Default: 80
    MinValue: 1
    MaxValue: 99
    ConstraintDescription: Must be a percentage between 1-99%

  DatabaseAlarmReadLatencyMaxSeconds:
    Description: Read latency max for alarm
    Type: Number
    Default: 1
    MinValue: 1

  DatabaseAlarmWriteLatencyMaxSeconds:
    Description: Write latency max for alarm
    Type: Number
    Default: 1
    MinValue: 1

  DatabaseAlarmEvaluationPeriods:
    Description: The number of periods over which data is compared to the specified threshold
    Type: Number
    Default: 2
    MinValue: 2

  DatabaseAlarmEvaluationPeriodSeconds:
    Description: The time over which the specified statistic is applied. Specify time in seconds, in multiples of 60. Enhanced monitoring must be enabled if less than 500 seconds
    Type: Number
    Default: 300
    MinValue: 60
    ConstraintDescription: Must be at least 60 seconds

  TcpPort:
    Description: Enter RDS Listening TCP Port number.
    Type: Number
    Default: 3306

  EnhancedMonitoring:
    Default: false
    Type: String
    Description: The optional flag for enhanced monitoring 
    ConstraintDescription: Only true or false are allowed
    AllowedValues:
      - true
      - false

  EnableAlarms:
    Default: false
    Type: String
    Description: Set to true to enable 
    ConstraintDescription: Only true or false are allowed
    AllowedValues:
      - true
      - false


Conditions:

  IsProd: !Equals [ !Ref EnvironmentName, prod ]

  AlarmsEnabled: !Equals [ !Ref EnableAlarms, true ]
  HasDBSnapshotIdentifier: !Not [!Equals [!Ref DBSnapshotIdentifier, '']]
  #HasDBOptionGroupName: !Not [!Equals [!Ref DBOptionGroupName, '']]
  #HasDBParameterGroupName: !Not [!Equals [!Ref DBParameterGroupName, '']]

  EnhancedMonitoringSupprtedAndEnabled: !And
    - !Condition AlarmsEnabled
    - !Equals [ !Ref EnhancedMonitoring, true ]



Resources:

  EnhancedMonitoringRole:
    Type: AWS::IAM::Role
    Condition: EnhancedMonitoringSupprtedAndEnabled
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  DatabaseAlarmTopic:
    Type: AWS::SNS::Topic
    Condition: AlarmsEnabled
    Properties:
     DisplayName: Database Alarm Topic

  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Database subnet group
      SubnetIds:
      - Fn::ImportValue: !Sub PrivateSubnet1
      - Fn::ImportValue: !Sub PrivateSubnet2
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
  
  DatabaseSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      VpcId: {'Fn::ImportValue': !Sub 'VPC'}
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: {'Fn::ImportValue': 'DatabaseSecurityGroup'}

  Database:
    DeletionPolicy: Snapshot # default
    UpdateReplacePolicy: Snapshot
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VPCSecurityGroups:
      - !Ref DatabaseSecurityGroup
      Engine: !Ref DBEngine
      DBName:  !Join 
        - ''
        - - !Ref Partition
          - !Ref EnvironmentValue
          - !Ref Partition
          - RDS
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref Partition
              - !Ref EnvironmentValue
              - !Ref Partition
              - RDS
        - Key: Technical Owner
          Value: !Ref TechnicalOwner
        - Key: Application
          Value: !Ref Application
        - Key: Environment
          Value: !Ref EnvironmentValue
        - Key: Tier
          Value: Application

      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DatabaseSize
      StorageType: !Ref StorageType
#      ProvisionedIopsValue: !Ref ProvisionedIopsValue
      MultiAZ: !Ref DBMultiAZ
      StorageEncrypted: !Ref EncryptionAtRest
      Port: !Ref TcpPort
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      PubliclyAccessible: !Ref PubliclyAccessible
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      PreferredBackupWindow: !Ref PreferredBackupWindow
      DeletionProtection: !Ref DeletionProtection
      #PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      #DBParameterGroupName: !If [HasDBParameterGroupName, !Ref DBParameterGroupName, !Ref 'AWS::NoValue']
      #DBOptionGroupName: !If [HasDBOptionGroupName, !Ref DBOptionGroupName, !Ref 'AWS::NoValue']
      DBSnapshotIdentifier: !If [HasDBSnapshotIdentifier, !Ref DBSnapshotIdentifier, !Ref 'AWS::NoValue']
      EnableIAMDatabaseAuthentication: !Ref EnableIAMDatabaseAuthentication
      CopyTagsToSnapshot: true
      MonitoringInterval: !If [ EnhancedMonitoringSupprtedAndEnabled, 60, 0 ]
      MonitoringRoleArn: !If [ EnhancedMonitoringSupprtedAndEnabled, !GetAtt EnhancedMonitoringRole.Arn, !Ref "AWS::NoValue" ]


  DatabaseCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB CPU utilization is over ${DatabaseAlarmMaxCpuPercent}% for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmMaxCpuPercent
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref Database
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: Database

  DatabaseFreeStorageSpaceAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB free storage space is less than ${DatabaseAlarmMinFreeSpaceInBytes} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: FreeStorageSpace
      Unit: Bytes
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmMinFreeSpaceInBytes
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref Database
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: Database

  DatabaseSwapUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB swap usage is greater than than ${DatabaseAlarmSwapUsageInBytes} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: SwapUsage
      Unit: Bytes
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmSwapUsageInBytes
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref Database
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: Database

  DatabaseReadLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB read latency is over ${DatabaseAlarmReadLatencyMaxSeconds} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: ReadLatency
      Unit: Seconds
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmReadLatencyMaxSeconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref Database
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: Database

  DatabaseWriteLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB write latency is over ${DatabaseAlarmWriteLatencyMaxSeconds} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: WriteLatency
      Unit: Seconds
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmWriteLatencyMaxSeconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref Database
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: Database


Outputs:

  Name:
    Description: RDS Stack Name
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-Name

  RdsDbId:
    Description: RDS Database ID
    Value: !Ref Database
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseID

  DbUser:
    Description: RDS Database admin account user
    Value: !Ref DatabaseUser
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseUser

  DbPassword:
    Description: RDS Database admin account password
    Value: !Ref DatabasePassword
    Export:
      Name: !Sub ${AWS::StackName}-DatabasePassword

  SecurityGroupId:
    Description: 'The security group used to manage access to RDS'
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  DatabaseAlarmTopicArn:
    Description: Database Alarm Topic ARN
    Condition: AlarmsEnabled
    Value: !Ref DatabaseAlarmTopic
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseAlarmTopicArn

  DatabaseAlarmTopicName:
    Description: Database Alarm Topic Name
    Condition: AlarmsEnabled
    Value: !GetAtt DatabaseAlarmTopic.TopicName
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseAlarmTopicName